const Lang = {
  en: {
    add: 'Add',
    purchase: 'Purchase',
    total: 'Total',
    price: 'Price',
    order: 'Order',
    order_confirm: 'Your order has been received',
    address: 'Address',
    name: 'Name and surname',
    postcode: 'Postal Code',
    country: 'Country',
    phone: 'Phone',
    email: 'Email',
    company_details: 'Company details',
    companies_only: 'For companies only.',
    company_name: 'Company name',
    company_number: 'Company registration number',
    vat_id: 'VAT ID',
    shipping_address: 'Alternate shipping address',
    shipping_postcode: 'Shipping postal code',
    shipping_notes: 'Enter if you wish to have the items delivered to a different address, workplace or construction site.',
    confirm_order: 'Confirm order',
    cartdata: 'Order'
  },
  sk: {
    add: 'Pridaj',
    purchase: 'Objednaj',
    total: 'Spolu',
    price: 'Cena',
    order: 'Objednávka',
    order_confirm: 'Vašu objednávku sme prijali',
    address: 'Adresa',
    name: 'Meno a priezvisko',
    postcode: 'PSČ',
    country: 'Štát',
    phone: 'Telefón',
    email: 'E-mail',
    company_details: 'Firemné údaje',
    companies_only: 'Len pre firmy.',
    company_name: 'Meno firmy',
    company_number: 'IČO',
    vat_id: 'DIČ',
    shipping_address: 'Iná dodacia adresa',
    shipping_postcode: 'PSČ dodania',
    shipping_notes: 'Zadajte ak si želáte tovar doručiť na inú adresu, do práce alebo na stavbu.',
    confirm_order: 'Potvrď objednávku',
    cartdata: 'Objednávka'
  }
}
